version: "3.9"
services:
  web:
    build: .
    volumes:
      - ./dist/:/var/www/html/
    ports:
      - 8080:80
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
  db:
    image: mariadb
    restart: always
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
      MYSQL_DATABASE: php-ts
